# .pre-commit-config.yaml
repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff (uv)
        entry: uv run ruff check . --fix
        language: system
        pass_filenames: false

      - id: ruff-format
        name: ruff-format (uv)
        entry: uv run ruff format .
        language: system
        pass_filenames: false

      - id: mypy
        name: mypy (uv)
        entry: uv run mypy src
        language: system
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
