repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^mkdocs\.yml$   # exclude mkdocs.yml so mermaid plugin tag won't trip it
      - id: check-added-large-files
        exclude: \.adi$          # exclude *.adi files everywhere (local + CI)

  # Java tools (local hooks example)
  - repo: local
    hooks:
      - id: google-java-format
        name: google-java-format
        entry: google-java-format --replace
        language: system
        types: [java]

      - id: checkstyle
        name: checkstyle
        entry: checkstyle -c /google_checks.xml
        language: system
        types: [java]

      - id: spotbugs
        name: spotbugs
        entry: spotbugs
        language: system
        types: [java]

      - id: pmd
        name: pmd
        entry: pmd -d src/main/java -R rulesets/java/quickstart.xml -f text
        language: system
        types: [java]
