# .pre-commit-config.yaml
repos:
  # Ruff (lint + format)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  # Basic hygiene hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-json
      - id: check-toml
      - id: check-added-large-files

  # Mypy (use the same config as local `uv run mypy`)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        args:
          - --config-file=pyproject.toml
        # Add any stubs/plugins your code relies on so the hook env resolves types
        additional_dependencies:
          - pydantic<2
          - types-click>=7.1.8
