site_name: ADIF MCP
site_url: https://adif-mcp.com/
repo_url: https://github.com/KI7MT/adif-mcp
site_description: ADIF MCP Documentation

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - search.suggest
    - search.highlight
    - content.code.copy
nav:
  - Home: index.md
  - Concepts:
    - Overview: concepts/overview.md
    - ADIF Basics: concepts/adif-basics.md
  - MCP:
    - Overview: mcp/overview.md
    - Manifest: mcp/manifest.md
    - Tools: mcp/tools.md
  - Integrations:
    - Overview: integrations/overview.md
    - LoTW: integrations/lotw.md
    - eQSL: integrations/eqsl.md
  - Plugins:
    - eQSL API: plugins/eqsl/api.md
    - LoTW API: plugins/lotw/api.md
  - User Guide:
    - userguide/getting-started.md
  - Dev Guide:
    - devguide/overview.md
  - Program ID Policy: program-id-policy.md
  - Spec:
    - Overview: spec/spec.md
  - Roadmap: roadmap.md




plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google   # or "numpy", both supported
            show_source: true
            show_root_toc_entry: false
            heading_level: 2
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - attr_list
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  - pymdownx.superfences
  - toc:
      permalink: true
