site_name: ADIF MCP
site_url: https://adif-mcp.com/
repo_url: https://github.com/KI7MT/adif-mcp
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - search.suggest
    - search.highlight
    - content.code.copy
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
nav:
  - Home: index.md
  - Spec:
    - Overview: spec/spec.md
  - Integrations:
    - LoTW: integrations/lotw.md
    - eQSL: integrations/eqsl.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google   # or "numpy", both supported
            show_source: true
            show_root_toc_entry: false
            heading_level: 2
