site_name: ADIF MCP
site_url: https://adif-mcp.com/
repo_url: https://github.com/KI7MT/adif-mcp
site_description: ADIF MCP Documentation
use_directory_urls: true

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - search.suggest
    - search.highlight
    - content.code.copy
nav:
  - Home: index.md
  - MCP:
    - Overview: mcp/overview.md
    - Manifest: mcp/manifest.md
    - Tools: mcp/tools.md
  - Integrations:
    - Overview: integrations/overview.md
    - LoTW: integrations/lotw/index.md
    - eQSL: integrations/eqsl/index.md
  - User Guide:
    - userguide/getting-started.md
  - Dev Guide:
    - Overview: devguide/overview.md
    - Make Commands: devguide/make-commands.md
  - Program ID Policy: program-id-policy.md
  - Spec:
    - Overview: spec/spec.md
  - Concepts:
    - Overview: concepts/overview.md
    - ADIF Basics: concepts/adif-basics.md
  - Roadmap: roadmap.md

#
# Sitemaps isn't working, but when it does, add this later to the root directory
# User-agent: *
# Allow: /
# Sitemap: https://adif-mcp.com/sitemap.xml
#
plugins:
  - search
  - mermaid2:
      javascript: https://unpkg.com/mermaid@10/dist/mermaid.min.js
      arguments:
        theme: default
#  - sitemap # remveod as UV can seem to install it. Leve commented out.
  - redirects:
      redirect_maps:
        lotw.md: integrations/lotw/index.md
        eqsl.md: integrations/eqsl/index.md
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google   # or "numpy", both supported
            show_source: true
            show_root_toc_entry: false
            heading_level: 2

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - toc:
      permalink: true
