site_name: ADIF MCP
site_description: ADIF MCP Documentation
site_url: https://adif-mcp.com/
repo_url: https://github.com/KI7MT/adif-mcp
edit_uri: edit/main/docs/
use_directory_urls: true

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - search.suggest
    - search.highlight
    - content.code.copy
nav:
nav:
  - Home: index.md
  - Concepts:
      - Why ADIF-MCP Matters: concepts/why-matters.md
      - Choice of LLMs: concepts/choice-of-llms.md
  - 'User Guide':
    - User Credentials: userguide/persona-management.md
    - Award Queries: userguide/awards.md
  - Dev Guide:
    - Dev Env Setup: dev/dev-env-setup.md
    - Provider Shemas: dev/provider-schemas.md
    - Probes: dev/probes.md
    - Git Commits: dev/git-commits.md
    - Command Reference: dev/command-reference.md
    - Code Snippets: dev/code-snippets.md
    - Dev Plan: dev/dev-plan.md
  - Program-ID: program-id-policy.md
  - Roadmap: roadmap.md
  - '':
    - Specs: spec/spec.md
  - '':
    - Overview: integrations/overview.md
    - LoTW: integrations/lotw/index.md
    - eQSL: integrations/eqsl/index.md
  - '':
    - Overview: mcp/overview.md
    - Manifest: mcp/manifest.md
    - Tools: mcp/tools.md


plugins:
  - search
  - mermaid2:
      arguments:
        theme: default
  - git-revision-date-localized:
      type: timeago
      fallback_to_build_date: true
      enable_creation_date: false
      timezone: UTC
  - redirects:
      redirect_maps:
        lotw.md: integrations/lotw/index.md
        eqsl.md: integrations/eqsl/index.md
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google   # or "numpy", both supported
            show_source: true
            show_root_toc_entry: false
            heading_level: 2

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - toc:
      permalink: true
