site_name: ADIF MCP
site_description: Model Context Protocol tools for Amateur Radio logging — ADIF core + LoTW/eQSL integrations
site_url: https://adif-mcp.com/
repo_url: https://github.com/KI7MT/adif-mcp
edit_uri: edit/main/docs/
site_dir: docs

theme:
  name: material
  language: en
  palette:
    primary: indigo
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Concepts:
      - Overview: concepts/overview.md
      - ADIF Basics: concepts/adif-basics.md
  - MCP:
      - Manifest & Types: mcp/manifest.md
      - Tools (API Surface): mcp/tools.md
  - Plugins:
      - LoTW:
          - Overview: plugins/lotw/index.md
          - API: plugins/lotw/api.md
      - eQSL:
          - Overview: plugins/eqsl/index.md
          - API: plugins/eqsl/api.md
  - Roadmap: roadmap.md
  - Changelog: changelog.md

plugins:
  - search

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - attr_list
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/KI7MT/adif-mcp
