/*
 * This file was generated by the Gradle 'init' task.
 *
 *  The settings file is used to specify which projects to include in your build.
 *  For more detailed information on multi-project builds, please refer
 *  to https://docs.gradle.org/9.0.0/userguide/multi_project_builds.html in the
 *  Gradle documentation.
 */

// Gradle settings for adif-mcp
// settings.gradle.kts — single-project
// Put pluginManagement FIRST (or omit entirely if not needed)

pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
    }
}

rootProject.name = "adif-mcp"

// No includes for single-project
