name: ci
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Sync deps (frozen, incl. dev tools)
        run: uv sync --group dev --frozen

      - name: Lint (ruff)
        run: uv run ruff check .

      - name: Type-check (mypy)
        run: uv run mypy src

      - name: Tests (pytest)
        env:
          PYTHONWARNINGS: error
        run: uv run pytest -q

      - name: Validate MCP manifest(s)
        run: make manifest

      - name: Fetch tags
        run: git fetch --tags --force --prune

      - name: Read project version (pyproject)
        id: pj
        run: echo "version=$(uv run cz version --project)" >> "$GITHUB_OUTPUT"

      - name: Read latest git tag
        id: tag
        run: echo "tag=$(git describe --tags --abbrev=0 2>/dev/null || echo none)" >> "$GITHUB_OUTPUT"

      - name: Enforce pyproject == latest tag (when tag exists)
        if: steps.tag.outputs.tag != 'none'
        run: |
          PJ="v${{ steps.pj.outputs.version }}"
          TG="${{ steps.tag.outputs.tag }}"
          echo "pyproject: ${PJ}"
          echo "latest tag: ${TG}"
          test "$PJ" = "$TG" || { echo "::error ::Version mismatch"; exit 1; }

      - name: Enforce pushed tag matches pyproject (only on tag pushes)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          PJ="v$(uv run cz version --project)"
          TAG="${GITHUB_REF#refs/tags/}"
          echo "pyproject: ${PJ}"
          echo "pushed tag: ${TAG}"
          test "$PJ" = "$TAG" || { echo "::error ::Tag mismatch"; exit 1; }
