name: Manifest Validate

on:
  push:
    paths:
      - "**/manifest.json"
      - ".github/workflows/manifest-validate.yml"
      - "src/adif_mcp/tools/validate_manifest.py"
      - "src/adif_mcp/resources/schemas/manifest.v1.json"
  pull_request:
    paths:
      - "**/manifest.json"
      - ".github/workflows/manifest-validate.yml"
      - "src/adif_mcp/tools/validate_manifest.py"
      - "src/adif_mcp/resources/schemas/manifest.v1.json"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    name: Validate MCP manifests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Find manifests
        id: find
        shell: bash
        run: |
          mapfile -t FILES < <(git ls-files | grep -E '(^|/)manifest\.json$' || true)
          if [ ${#FILES[@]} -eq 0 ]; then
            echo "No manifest.json files found."
            echo "count=0" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          printf '%s\n' "${FILES[@]}"
          printf 'files<<EOF\n%s\nEOF\n' "$(printf '%s\n' "${FILES[@]}")" >> "$GITHUB_OUTPUT"
          echo "count=${#FILES[@]}" >> "$GITHUB_OUTPUT"

      # Install uv before any uv run calls
      - name: Install uv
        uses: astral-sh/setup-uv@v1
        with:
          version: latest

      - name: Set up Python
        if: steps.find.outputs.count != '0'
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Sync deps (prefer dev group; frozen if lock)
        run: |
          set -e
          uv --version || true
          if [ -f uv.lock ]; then
            uv sync --group dev --frozen || uv sync --frozen || uv sync
          else
            uv sync --group dev || uv sync
          fi

      # Ensure the *new* schema location exists
      - name: Ensure schema exists
        if: steps.find.outputs.count != '0'
        run: |
          test -f src/adif_mcp/resources/schemas/manifest.v1.json

      - name: Validate JSON syntax (jq)
        if: steps.find.outputs.count != '0'
        run: |
          sudo apt-get update -y && sudo apt-get install -y jq
          ok=1
          while IFS= read -r f; do
            echo "🔎 jq lint: $f"
            if ! jq empty "$f"; then
              echo "::error file=$f::Invalid JSON"
              ok=0
            fi
          done <<< "${{ steps.find.outputs.files }}"
          [ $ok -eq 1 ] || exit 1

      # Use the in-package validator module (new location)
      - name: Validate against MCP schema
        if: steps.find.outputs.count != '0'
        run: |
          uv run python -m adif_mcp.tools.validate_manifest ${{ steps.find.outputs.files }}

      - name: Summary
        if: steps.find.outputs.count != '0'
        run: echo "✅ Validated ${{ steps.find.outputs.count }} manifest file(s)."
