name: pre-commit

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - 'site/**'
  pull_request:
    branches: [ main ]

concurrency:
  group: pre-commit-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install uv so local hooks like `entry: uv run ruff ...` work
      - name: Install uv
        uses: astral-sh/setup-uv@v1
        with:
          version: latest

      # Ensure dev tools are available for your uv hooks
      - name: Sync deps for hooks
        run: |
          set -e
          uv --version
          if [ -f uv.lock ]; then
            uv sync --group dev --frozen || uv sync --frozen || uv sync
          else
            uv sync --group dev || uv sync
          fi

      # (Optional) cache pre-commit envs for speed — must run BEFORE the action
      - name: Cache pre-commit envs
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-${{ runner.os }}-

      # Run pre-commit (this action installs `pre-commit` for you)
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files --show-diff-on-failure --color=always
