name: Pre-commit Checks

on:
  push:
    branches: [ java ]
    paths-ignore:
      - 'docs/**'
      - 'site/**'
      - '*.adi'      # exclude ADIF logs from CI triggers too
  pull_request:
    branches: [ java ]

jobs:
  precommit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Install Pre-commit
        run: |
          sudo apt-get install -y pre-commit

      - name: Run Pre-commit
        run: pre-commit run --all-files


# Explanation of the Workflow
# - name: The name of the workflow is set to "Pre-commit Checks."
#   - on: Specifies the events that trigger the workflow, which are pushes and pull requests to the main and develop branches.
#   - jobs: Defines the jobs that will run in the workflow.
#     - precommit: The job that runs the pre-commit checks.
#       - runs-on: Specifies the environment to run the job, set to ubuntu-latest.
#       - steps: The sequence of steps to execute in the job.
#         - Checkout code: Uses the actions/checkout action to check out your repository's code.
#         - Set up JDK: Uses the actions/setup-java action to set up the specified version of Java (in this case, Java 21).
#         - Install Pre-commit: Installs pre-commit using apt-get.
#         - Run Pre-commit: Executes the pre-commit hooks on all files.
