name: pre-commit

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - 'site/**'
  pull_request:
    branches: [ main ]

# Avoid overlapping runs on the same PR/branch
concurrency:
  group: pre-commit-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@v1
        with:
          version: latest

      - name: Sync deps for hooks
        run: |
          uv --version
          uv sync --group dev --frozen || uv sync --frozen || uv sync

      - name: Run pre-commit
        run: pre-commit run --show-diff-on-failure --color=always --all-files

      # Optional: cache pre-commit envs for speed
      - name: Cache pre-commit envs
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-${{ runner.os }}-

      # Run pre-commit hooks (uses your .pre-commit-config.yaml)
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
