name: release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build sdist+wheel
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Sync deps (frozen)
        run: uv sync --frozen

      - name: Verify tag matches pyproject version
        run: |
          TAG="${GITHUB_REF_NAME#v}"
          echo "Tag version: $TAG"
          PY_VER=$(python -c "import tomllib; print(tomllib.load(open('pyproject.toml','rb'))['project']['version'])")
          echo "pyproject version: $PY_VER"
          [ "$TAG" = "$PY_VER" ] || { echo "::error::Tag ($TAG) != pyproject version ($PY_VER)"; exit 1; }

      - name: Commitizen message check (since previous tag)
        run: |
          set -e

          # Ensure we have all tags (defense-in-depth)
          git fetch --tags --force --prune

          CUR_SHA="$(git rev-parse "$GITHUB_SHA")"

          # Previous tag *before* the current tag; tolerates annotated/lightweight tags
          PREV_TAG="$(git describe --tags --abbrev=0 --match 'v*' "${CUR_SHA}^" 2>/dev/null || true)"

          if [ -z "$PREV_TAG" ]; then
            # First release or no previous semver-like tag: check only the tagged commit
            RANGE="${CUR_SHA}~1..${CUR_SHA}"
          else
            RANGE="${PREV_TAG}..${CUR_SHA}"
          fi

          echo "Commitizen checking rev-range: $RANGE"

          COUNT="$(git rev-list --count "$RANGE" || echo 0)"
          if [ "$COUNT" -eq 0 ]; then
            echo "No commits to check in range (likely an annotated tag only). Skipping cz check."
            exit 0
          fi

          uv run cz check --rev-range "$RANGE"

      - name: Build artifacts
        run: uv build

      - name: Upload dist/
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  publish-testpypi:
    name: Publish to TestPyPI (pre-releases)
    if: >
      startsWith(github.ref_name, 'v') &&
      (contains(github.ref_name, 'a') || contains(github.ref_name, 'b') || contains(github.ref_name, 'rc'))
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  publish-pypi:
    name: Publish to PyPI (final)
    if: >
      startsWith(github.ref_name, 'v') &&
      !contains(github.ref_name, 'a') &&
      !contains(github.ref_name, 'b') &&
      !contains(github.ref_name, 'rc')
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1

  github-release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write   # needed to create a Release
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      # Create the release from the current tag and upload artifacts
      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}          # e.g. v0.1.14
          name: ${{ github.ref_name }}              # Release name
          generate_release_notes: true              # auto notes
          files: |
            dist/*.whl
            dist/*.tar.gz
