name: release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build sdist+wheel
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # we need full history & tags for cz checks

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Sync deps (frozen)
        run: uv sync --frozen

      # ---- Strict CC check on the commits being released ----
      - name: Commitizen message check (since previous tag)
        run: |
          set -e
          CUR_SHA="$(git rev-parse "$GITHUB_SHA")"

          # previous tag (2nd most recent by version sort)
          PREV_TAG="$(git tag --sort=-version:refname | sed -n '2p' || true)"

          if [ -z "$PREV_TAG" ]; then
            # first release: check just the tagged commit
            RANGE="${CUR_SHA}~1..${CUR_SHA}"
          else
            RANGE="${PREV_TAG}..${CUR_SHA}"
          fi

          echo "Commitizen checking rev-range: $RANGE"

          COUNT="$(git rev-list --count "$RANGE" || echo 0)"
          if [ "$COUNT" -eq 0 ]; then
            echo "No commits to check in range (likely an annotated tag only). Skipping cz check."
            exit 0
          fi

          uv run cz check --rev-range "$RANGE"

      # ---- Ensure tag matches pyproject version ----
      - name: Verify tag matches pyproject version
        run: |
          TAG="${GITHUB_REF_NAME#v}"
          echo "Tag version: $TAG"
          PY_VER=$(python -c "import tomllib; print(tomllib.load(open('pyproject.toml','rb'))['project']['version'])")
          echo "pyproject version: $PY_VER"
          [ "$TAG" = "$PY_VER" ] || { echo "::error::Tag ($TAG) != pyproject version ($PY_VER)"; exit 1; }

      - name: Build artifacts
        run: uv build

      - name: Upload dist/
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  publish-testpypi:
    name: Publish to TestPyPI (pre-releases)
    if: >
      startsWith(github.ref_name, 'v') &&
      (contains(github.ref_name, 'a') || contains(github.ref_name, 'b') || contains(github.ref_name, 'rc'))
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  publish-pypi:
    name: Publish to PyPI (final)
    if: >
      startsWith(github.ref_name, 'v') &&
      !contains(github.ref_name, 'a') &&
      !contains(github.ref_name, 'b') &&
      !contains(github.ref_name, 'rc')
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
