name: release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build sdist+wheel
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Sync deps (frozen)
        run: uv sync --frozen

      - name: Build artifacts
        run: uv build

      - name: Upload dist/
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  publish-testpypi:
    name: Publish to TestPyPI (pre-releases)
    if: >
      startsWith(github.ref_name, 'v') &&
      contains(github.ref_name, 'a') || contains(github.ref_name, 'b') || contains(github.ref_name, 'rc')
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write   # required for Trusted Publishers
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  publish-pypi:
    name: Publish to PyPI (final)
    if: >
      startsWith(github.ref_name, 'v') &&
      !contains(github.ref_name, 'a') &&
      !contains(github.ref_name, 'b') &&
      !contains(github.ref_name, 'rc')
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write   # required for Trusted Publishers
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
