name: release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build sdist+wheel
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Sync deps (frozen)
        run: uv sync --frozen

      # Ensure tag matches pyproject version
      - name: Verify tag matches pyproject version
        run: |
          TAG="${GITHUB_REF_NAME#v}"
          echo "Tag version: $TAG"
          python - <<'PY'
          import os, tomllib, sys
          with open("pyproject.toml","rb") as f:
              pv = tomllib.load(f)["project"]["version"]
          print("pyproject version:", pv)
          sys.exit(0 if pv == os.environ["GITHUB_REF_NAME"][1:] else 1)
          PY

      - name: Build artifacts
        run: uv build

      - name: Upload dist/
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  publish-testpypi:
    name: Publish to TestPyPI (pre-releases)
    if: >
      startsWith(github.ref_name, 'v') &&
      (contains(github.ref_name, 'a') || contains(github.ref_name, 'b') || contains(github.ref_name, 'rc'))
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  publish-pypi:
    name: Publish to PyPI (final)
    if: >
      startsWith(github.ref_name, 'v') &&
      !contains(github.ref_name, 'a') &&
      !contains(github.ref_name, 'b') &&
      !contains(github.ref_name, 'rc')
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
